/* This file was generated by lus2lic version master.671 (480ff8adfdc23a03f88ab2796a74a7ecb75975f1). */
/*  lus2lic -2cw7 -2cns ../convertible.lus -n main */
/* on ovaz the 21/11/2016 at 13:49:49 */
#include "convertible_main.h"
                              
                              #define tickBegin  0xe0000000
                              #define _Start	 0xe0000008
#define _Parked	 0xe0000010
#define _Rot	 0xe0000018
#define _Tic	 0xe0000020
#define _OnOff	 0xe0000028
#define _Done	 0xe0000030
#define _Distance	 0xe0000038
#define _Danger	 0xe0000040
#define _Locked	 0xe0000048
#define _Speed	 0xe0000050
#define _Hood_Speed	 0xe0000058

 int main(){

  _boolean Start;
  _boolean Parked;
  _boolean Rot;
  _boolean Tic;
  _boolean OnOff;
  _boolean Done;
  _real Distance;
  _boolean Danger;
  _boolean Locked;
  _real Speed;
  _real Hood_Speed;
  convertible_main_ctx_type ctx_struct;
  convertible_main_ctx_type* ctx = &ctx_struct;
  convertible_main_ctx_init(ctx);
          /* Main loop */
          while(1){
          // notify the simulator that it is time to load the inputs from Lurette
          // to the specified address
          *((unsigned int*)tickBegin) = 0;
          // load inputs from the memory locations
              Start = *((_boolean *)_Start);
    Parked = *((_boolean *)_Parked);
    Rot = *((_boolean *)_Rot);
    Tic = *((_boolean *)_Tic);
    OnOff = *((_boolean *)_OnOff);
    Done = *((_boolean *)_Done);
    Distance = *((_real *)_Distance);
    convertible_main_step(Start,Parked,Rot,Tic,OnOff,Done,Distance,&Danger,&Locked,&Speed,&Hood_Speed,ctx);

// now write the output to the memory which will be output to Lurette
	 *((_boolean *)_Danger) = Danger;
	 *((_boolean *)_Locked) = Locked;
	 *((_real *)_Speed) = Speed;
	 *((_real *)_Hood_Speed) = Hood_Speed;
}
  return 1;       
        }        
        