/* This file was generated by lus2lic version master.671 (480ff8adfdc23a03f88ab2796a74a7ecb75975f1). */
/*  lus2lic -2cw7 -2cns ../convertible.lus -n main */
/* on ovaz the 21/11/2016 at 13:49:49 */
#include "convertible_main.h"
//// Defining step functions
// Memory initialisation for Lustre_arrow_4_ctx
void Lustre_arrow_4_ctx_reset(Lustre_arrow_4_ctx_type* ctx){
  int _i;
  ctx->_memory = _true;
}

// Initialisation of the  internal structure of Lustre_arrow_4_ctx
void Lustre_arrow_4_ctx_init(Lustre_arrow_4_ctx_type* ctx){
  // ctx->client_data = cdata;
  Lustre_arrow_4_ctx_reset(ctx);
 }
// Step function(s) for Lustre_arrow_4_ctx
void Lustre_arrow_4_step(_integer x,_integer y,_integer *z,Lustre_arrow_4_ctx_type* ctx){  *z = ((ctx->_memory)? x : y);
  ctx->_memory = _false;

} // End of Lustre_arrow_4_step

// Memory initialisation for Lustre_arrow_3_ctx
void Lustre_arrow_3_ctx_reset(Lustre_arrow_3_ctx_type* ctx){
  int _i;
  ctx->_memory = _true;
}

// Initialisation of the  internal structure of Lustre_arrow_3_ctx
void Lustre_arrow_3_ctx_init(Lustre_arrow_3_ctx_type* ctx){
  // ctx->client_data = cdata;
  Lustre_arrow_3_ctx_reset(ctx);
 }
// Step function(s) for Lustre_arrow_3_ctx
void Lustre_arrow_3_step(_real x,_real y,_real *z,Lustre_arrow_3_ctx_type* ctx){  *z = ((ctx->_memory)? x : y);
  ctx->_memory = _false;

} // End of Lustre_arrow_3_step

// Memory initialisation for Lustre_arrow_2_ctx
void Lustre_arrow_2_ctx_reset(Lustre_arrow_2_ctx_type* ctx){
  int _i;
  ctx->_memory = _true;
}

// Initialisation of the  internal structure of Lustre_arrow_2_ctx
void Lustre_arrow_2_ctx_init(Lustre_arrow_2_ctx_type* ctx){
  // ctx->client_data = cdata;
  Lustre_arrow_2_ctx_reset(ctx);
 }
// Step function(s) for Lustre_arrow_2_ctx
void Lustre_arrow_2_step(convertible_hood_speed_state x,convertible_hood_speed_state y,convertible_hood_speed_state *z,Lustre_arrow_2_ctx_type* ctx){  *z = ((ctx->_memory)? x : y);
  ctx->_memory = _false;

} // End of Lustre_arrow_2_step

// Memory initialisation for Lustre_arrow_ctx
void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx){
  int _i;
  ctx->_memory = _true;
}

// Initialisation of the  internal structure of Lustre_arrow_ctx
void Lustre_arrow_ctx_init(Lustre_arrow_ctx_type* ctx){
  // ctx->client_data = cdata;
  Lustre_arrow_ctx_reset(ctx);
 }
// Step function(s) for Lustre_arrow_ctx
void Lustre_arrow_step(convertible_hood_state x,convertible_hood_state y,convertible_hood_state *z,Lustre_arrow_ctx_type* ctx){  *z = ((ctx->_memory)? x : y);
  ctx->_memory = _false;

} // End of Lustre_arrow_step

// Memory initialisation for Lustre_arrow_6_ctx
void Lustre_arrow_6_ctx_reset(Lustre_arrow_6_ctx_type* ctx){
  int _i;
  ctx->_memory = _true;
}

// Initialisation of the  internal structure of Lustre_arrow_6_ctx
void Lustre_arrow_6_ctx_init(Lustre_arrow_6_ctx_type* ctx){
  // ctx->client_data = cdata;
  Lustre_arrow_6_ctx_reset(ctx);
 }
// Step function(s) for Lustre_arrow_6_ctx
void Lustre_arrow_6_step(convertible_vehicle_state x,convertible_vehicle_state y,convertible_vehicle_state *z,Lustre_arrow_6_ctx_type* ctx){  *z = ((ctx->_memory)? x : y);
  ctx->_memory = _false;

} // End of Lustre_arrow_6_step

// Memory initialisation for Lustre_arrow_5_ctx
void Lustre_arrow_5_ctx_reset(Lustre_arrow_5_ctx_type* ctx){
  int _i;
  ctx->_memory = _true;
}

// Initialisation of the  internal structure of Lustre_arrow_5_ctx
void Lustre_arrow_5_ctx_init(Lustre_arrow_5_ctx_type* ctx){
  // ctx->client_data = cdata;
  Lustre_arrow_5_ctx_reset(ctx);
 }
// Step function(s) for Lustre_arrow_5_ctx
void Lustre_arrow_5_step(_real x[50],_real y[50],_real z[50]/*out*/,Lustre_arrow_5_ctx_type* ctx){  _assign_rp50(z, ((ctx->_memory)? x : y), sizeof(_real [50]));
  ctx->_memory = _false;

} // End of Lustre_arrow_5_step

// Step function(s) for Lustre_eq_ctx
void Lustre_eq_step(_integer x,_integer y,_boolean *z){
  *z = (x == y);

} // End of Lustre_eq_step

// Step function(s) for Lustre_eq_2_ctx
void Lustre_eq_2_step(_real x,_real y,_boolean *z){
  *z = (x == y);

} // End of Lustre_eq_2_step

// Step function(s) for Lustre_eq_3_ctx
void Lustre_eq_3_step(convertible_hood_state x,convertible_hood_state y,_boolean *z){
  *z = (x == y);

} // End of Lustre_eq_3_step

// Step function(s) for Lustre_hat_ctx
void Lustre_hat_step(_real x,_real z[50]/*out*/){
  z[0] = x;
  z[1] = x;
  z[2] = x;
  z[3] = x;
  z[4] = x;
  z[5] = x;
  z[6] = x;
  z[7] = x;
  z[8] = x;
  z[9] = x;
  z[10] = x;
  z[11] = x;
  z[12] = x;
  z[13] = x;
  z[14] = x;
  z[15] = x;
  z[16] = x;
  z[17] = x;
  z[18] = x;
  z[19] = x;
  z[20] = x;
  z[21] = x;
  z[22] = x;
  z[23] = x;
  z[24] = x;
  z[25] = x;
  z[26] = x;
  z[27] = x;
  z[28] = x;
  z[29] = x;
  z[30] = x;
  z[31] = x;
  z[32] = x;
  z[33] = x;
  z[34] = x;
  z[35] = x;
  z[36] = x;
  z[37] = x;
  z[38] = x;
  z[39] = x;
  z[40] = x;
  z[41] = x;
  z[42] = x;
  z[43] = x;
  z[44] = x;
  z[45] = x;
  z[46] = x;
  z[47] = x;
  z[48] = x;
  z[49] = x;

} // End of Lustre_hat_step

// Memory initialisation for Lustre_pre_4_ctx
void Lustre_pre_4_ctx_reset(Lustre_pre_4_ctx_type* ctx){
  int _i;

}

// Initialisation of the  internal structure of Lustre_pre_4_ctx
void Lustre_pre_4_ctx_init(Lustre_pre_4_ctx_type* ctx){
  // ctx->client_data = cdata;
  Lustre_pre_4_ctx_reset(ctx);
 }
// Step function(s) for Lustre_pre_4_ctx
void Lustre_pre_4_get(_integer *z,Lustre_pre_4_ctx_type* ctx){
  *z = ctx->_memory;

} // End of Lustre_pre_4_get

void Lustre_pre_4_set(_integer x,Lustre_pre_4_ctx_type* ctx){
  ctx->_memory = x;

} // End of Lustre_pre_4_set

// Memory initialisation for Lustre_pre_3_ctx
void Lustre_pre_3_ctx_reset(Lustre_pre_3_ctx_type* ctx){
  int _i;

}

// Initialisation of the  internal structure of Lustre_pre_3_ctx
void Lustre_pre_3_ctx_init(Lustre_pre_3_ctx_type* ctx){
  // ctx->client_data = cdata;
  Lustre_pre_3_ctx_reset(ctx);
 }
// Step function(s) for Lustre_pre_3_ctx
void Lustre_pre_3_get(_real *z,Lustre_pre_3_ctx_type* ctx){
  *z = ctx->_memory;

} // End of Lustre_pre_3_get

void Lustre_pre_3_set(_real x,Lustre_pre_3_ctx_type* ctx){
  ctx->_memory = x;

} // End of Lustre_pre_3_set

// Memory initialisation for Lustre_pre_2_ctx
void Lustre_pre_2_ctx_reset(Lustre_pre_2_ctx_type* ctx){
  int _i;

}

// Initialisation of the  internal structure of Lustre_pre_2_ctx
void Lustre_pre_2_ctx_init(Lustre_pre_2_ctx_type* ctx){
  // ctx->client_data = cdata;
  Lustre_pre_2_ctx_reset(ctx);
 }
// Step function(s) for Lustre_pre_2_ctx
void Lustre_pre_2_get(convertible_hood_speed_state *z,Lustre_pre_2_ctx_type* ctx){
  *z = ctx->_memory;

} // End of Lustre_pre_2_get

void Lustre_pre_2_set(convertible_hood_speed_state x,Lustre_pre_2_ctx_type* ctx){
  ctx->_memory = x;

} // End of Lustre_pre_2_set

// Memory initialisation for Lustre_pre_ctx
void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx){
  int _i;

}

// Initialisation of the  internal structure of Lustre_pre_ctx
void Lustre_pre_ctx_init(Lustre_pre_ctx_type* ctx){
  // ctx->client_data = cdata;
  Lustre_pre_ctx_reset(ctx);
 }
// Step function(s) for Lustre_pre_ctx
void Lustre_pre_get(convertible_hood_state *z,Lustre_pre_ctx_type* ctx){
  *z = ctx->_memory;

} // End of Lustre_pre_get

void Lustre_pre_set(convertible_hood_state x,Lustre_pre_ctx_type* ctx){
  ctx->_memory = x;

} // End of Lustre_pre_set

// Memory initialisation for Lustre_pre_6_ctx
void Lustre_pre_6_ctx_reset(Lustre_pre_6_ctx_type* ctx){
  int _i;

}

// Initialisation of the  internal structure of Lustre_pre_6_ctx
void Lustre_pre_6_ctx_init(Lustre_pre_6_ctx_type* ctx){
  // ctx->client_data = cdata;
  Lustre_pre_6_ctx_reset(ctx);
 }
// Step function(s) for Lustre_pre_6_ctx
void Lustre_pre_6_get(convertible_vehicle_state *z,Lustre_pre_6_ctx_type* ctx){
  *z = ctx->_memory;

} // End of Lustre_pre_6_get

void Lustre_pre_6_set(convertible_vehicle_state x,Lustre_pre_6_ctx_type* ctx){
  ctx->_memory = x;

} // End of Lustre_pre_6_set

// Memory initialisation for Lustre_pre_5_ctx
void Lustre_pre_5_ctx_reset(Lustre_pre_5_ctx_type* ctx){
  int _i;

}

// Initialisation of the  internal structure of Lustre_pre_5_ctx
void Lustre_pre_5_ctx_init(Lustre_pre_5_ctx_type* ctx){
  // ctx->client_data = cdata;
  Lustre_pre_5_ctx_reset(ctx);
 }
// Step function(s) for Lustre_pre_5_ctx
void Lustre_pre_5_get(_real z[50]/*out*/,Lustre_pre_5_ctx_type* ctx){
  _assign_rp50(z, ctx->_memory, sizeof(_real [50]));

} // End of Lustre_pre_5_get

void Lustre_pre_5_set(_real x[50],Lustre_pre_5_ctx_type* ctx){
  _assign_rp50(ctx->_memory, x, sizeof(_real [50]));

} // End of Lustre_pre_5_set

// Step function(s) for Lustre_slash_ctx
void Lustre_slash_step(_real x,_real y,_real *z){
  *z = (x / y);

} // End of Lustre_slash_step

// Step function(s) for assign_50_ctx
void assign_50_step(_real v,_integer jv,_real t[50],_real nt[50]/*out*/){
   convertible_update_acc _v_3;
   convertible_update_acc dummy;

  _v_3.i = 0;
  _v_3.j = jv;
  _v_3.v = v;
  fillred_update_cell_do_50_step(_v_3,t,&dummy,nt); 

} // End of assign_50_step

// Step function(s) for convertible_abs_ctx
void convertible_abs_step(_real x,_real *y){
   _real _v_2;

/*
LUSDEF:_v_2
-x
LUSEND
*/
   _boolean _v_1;

/*
LUSDEF:_v_1
x>=0.0
LUSEND
*/

  _v_2 = - x;
  _v_1 = x >= 0.0;
   if (_v_1 == _true) {
     *y = x;
   } else {
     *y = _v_2;
   }

} // End of convertible_abs_step

// Step function(s) for convertible_braking_time_ctx
void convertible_braking_time_step(_real Speed,_real *res){
   _real _v_4;

/*
LUSDEF:_v_4
Speed*Speed
LUSEND
*/

  _v_4 = Speed * Speed;
  Lustre_slash_step(_v_4,5500.0,res); 

} // End of convertible_braking_time_step

// Memory initialisation for convertible_hood_ctx
void convertible_hood_ctx_reset(convertible_hood_ctx_type* ctx){
  int _i;

    convertible_hood_speed_ctx_reset(&ctx->convertible_hood_speed_ctx_tab[0]);
    Lustre_pre_ctx_reset(&ctx->Lustre_pre_ctx_tab[0]);
    Lustre_arrow_ctx_reset(&ctx->Lustre_arrow_ctx_tab[0]);
}

// Initialisation of the  internal structure of convertible_hood_ctx
void convertible_hood_ctx_init(convertible_hood_ctx_type* ctx){
  // ctx->client_data = cdata;
  convertible_hood_ctx_reset(ctx);
 }
// Step function(s) for convertible_hood_ctx
void convertible_hood_step(_boolean Tic,_boolean Parked,_boolean OnOff,_boolean Done,_boolean *Locked,_real *Hood_Speed,convertible_hood_ctx_type* ctx){   _real _v_12;

/*
LUSDEF:_v_12
(convertible::hood_speed(Tic_on_in_motion)) when st(convertible::in_motion)
LUSEND
*/
   _real _v_11;
   convertible_hood_state _v_10;

/*
LUSDEF:_v_10
(if _v_9 then convertible_locked else convertible_in_motion) when pst(convertible::in_motion)
LUSEND
*/
   _boolean _v_9;

/*
LUSDEF:_v_9
(_v_9=Done) when pst(convertible::in_motion)
LUSEND
*/
   convertible_hood_state _v_8;

/*
LUSDEF:_v_8
(if _v_7 then convertible_in_motion else convertible_locked) when pst(convertible::locked)
LUSEND
*/
   _boolean _v_7;

/*
LUSDEF:_v_7
(_v_7=_v_6) when pst(convertible::locked)
LUSEND
*/
   _boolean _v_6;

/*
LUSDEF:_v_6
OnOff and Parked
LUSEND
*/
   convertible_hood_state _v_5;

/*
LUSDEF:_v_5
pre(st)
LUSEND
*/
   convertible_hood_state pst;

/*
LUSDEF:pst
convertible_locked -> _v_5
LUSEND
*/
   convertible_hood_state st;

/*
LUSDEF:st
(st=_v_10) when pst(convertible::in_motion)
LUSEND
*/
   _boolean Tic_on_in_motion;

/*
LUSDEF:Tic_on_in_motion
(Tic_on_in_motion=Tic) when st(convertible::in_motion)
LUSEND
*/

  Lustre_pre_get(&_v_5,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_arrow_step(convertible_locked,_v_5,&pst,&ctx->Lustre_arrow_ctx_tab[0]); 
  if (pst == convertible_in_motion) {
  _v_9 = Done;
   if (_v_9 == _true) {
     _v_10 = convertible_locked;
   } else {
     _v_10 = convertible_in_motion;
   }
  st = _v_10;

  } else {
  }  _v_6 = OnOff & Parked;
  if (pst == convertible_locked) {
  _v_7 = _v_6;
   if (_v_7 == _true) {
     _v_8 = convertible_in_motion;
   } else {
     _v_8 = convertible_locked;
   }
  st = _v_8;

  } else {
  }  Lustre_pre_set(st,&ctx->Lustre_pre_ctx_tab[0]); 
  Lustre_eq_3_step(st,convertible_locked,Locked); 
  if (st == convertible_in_motion) {
  Tic_on_in_motion = Tic;
  convertible_hood_speed_step(Tic_on_in_motion,&_v_12,&ctx->convertible_hood_speed_ctx_tab[0]); 
  *Hood_Speed = _v_12;

  } else {
  if (st == convertible_locked) {
  _v_11 = 0.0;
  *Hood_Speed = _v_11;

  } else {
  }}
} // End of convertible_hood_step

// Memory initialisation for convertible_hood_speed_ctx
void convertible_hood_speed_ctx_reset(convertible_hood_speed_ctx_type* ctx){
  int _i;

    Lustre_pre_2_ctx_reset(&ctx->Lustre_pre_2_ctx_tab[0]);
    Lustre_pre_3_ctx_reset(&ctx->Lustre_pre_3_ctx_tab[0]);
    Lustre_pre_3_ctx_reset(&ctx->Lustre_pre_3_ctx_tab[1]);
    Lustre_arrow_2_ctx_reset(&ctx->Lustre_arrow_2_ctx_tab[0]);
    Lustre_arrow_3_ctx_reset(&ctx->Lustre_arrow_3_ctx_tab[0]);
    Lustre_arrow_3_ctx_reset(&ctx->Lustre_arrow_3_ctx_tab[1]);
}

// Initialisation of the  internal structure of convertible_hood_speed_ctx
void convertible_hood_speed_ctx_init(convertible_hood_speed_ctx_type* ctx){
  // ctx->client_data = cdata;
  convertible_hood_speed_ctx_reset(ctx);
 }
// Step function(s) for convertible_hood_speed_ctx
void convertible_hood_speed_step(_boolean Tic,_real *Hood_Speed,convertible_hood_speed_ctx_type* ctx){   _real _v_35;

/*
LUSDEF:_v_35
((_v_33+_v_34) when st(convertible::slow)) when Tic
LUSEND
*/
   _real _v_34;

/*
LUSDEF:_v_34
((_v_34=pHood_Percent) when st(convertible::slow)) when Tic
LUSEND
*/
   _real _v_33;

/*
LUSDEF:_v_33
((slow_it_down*_v_32) when st(convertible::slow)) when Tic
LUSEND
*/
   _real _v_32;

/*
LUSDEF:_v_32
((_v_32=kh) when st(convertible::slow)) when Tic
LUSEND
*/
   _real _v_31;

/*
LUSDEF:_v_31
((_v_31=_v_30) when st(convertible::fast)) when Tic
LUSEND
*/
   _real _v_30;

/*
LUSDEF:_v_30
(kh+pHood_Percent) when Tic
LUSEND
*/
   _real _v_29;

/*
LUSDEF:_v_29
((_v_29=_v_28) when st(convertible::slow)) when Tic
LUSEND
*/
   _real _v_28;

/*
LUSDEF:_v_28
((10.0*slow_it_down) when st(convertible::slow)) when Tic
LUSEND
*/
   _real _v_27;

/*
LUSDEF:_v_27
(_v_27=pHood_Speed) when not Tic
LUSEND
*/
   _real _v_26;

/*
LUSDEF:_v_26
pre(Hood_Speed)
LUSEND
*/
   _real _v_25;

/*
LUSDEF:_v_25
(5./0.1) when Tic
LUSEND
*/
   _real _v_24;

/*
LUSDEF:_v_24
((convertible::sqrt(_v_23)) when st(convertible::slow)) when Tic
LUSEND
*/
   _real _v_23;

/*
LUSDEF:_v_23
((_v_22/5.0) when st(convertible::slow)) when Tic
LUSEND
*/
   _real _v_22;

/*
LUSDEF:_v_22
((100.0-_v_21) when st(convertible::slow)) when Tic
LUSEND
*/
   _real _v_21;

/*
LUSDEF:_v_21
((_v_21=pHood_Percent) when st(convertible::slow)) when Tic
LUSEND
*/
   _real _v_20;

/*
LUSDEF:_v_20
(pre(Hood_Percent)) when Tic
LUSEND
*/
   convertible_hood_speed_state _v_19;

/*
LUSDEF:_v_19
((if _v_18 then convertible_slow else convertible_wait) when pst(convertible::slow)) when Tic
LUSEND
*/
   _boolean _v_18;

/*
LUSDEF:_v_18
((_v_17<100.0) when pst(convertible::slow)) when Tic
LUSEND
*/
   _real _v_17;

/*
LUSDEF:_v_17
((_v_17=pHood_Percent) when pst(convertible::slow)) when Tic
LUSEND
*/
   convertible_hood_speed_state _v_16;

/*
LUSDEF:_v_16
((if _v_15 then convertible_fast else convertible_slow) when pst(convertible::fast)) when Tic
LUSEND
*/
   _boolean _v_15;

/*
LUSDEF:_v_15
((_v_14<85.0) when pst(convertible::fast)) when Tic
LUSEND
*/
   _real _v_14;

/*
LUSDEF:_v_14
((_v_14=pHood_Percent) when pst(convertible::fast)) when Tic
LUSEND
*/
   convertible_hood_speed_state _v_13;

/*
LUSDEF:_v_13
(pre(st)) when Tic
LUSEND
*/
   convertible_hood_speed_state pst;

/*
LUSDEF:pst
(convertible_wait -> _v_13) when Tic
LUSEND
*/
   convertible_hood_speed_state st;

/*
LUSDEF:st
((st=_v_16) when pst(convertible::fast)) when Tic
LUSEND
*/
   _real kh;

/*
LUSDEF:kh
(100./_v_25) when Tic
LUSEND
*/
   _real Hood_Percent;

/*
LUSDEF:Hood_Percent
((Hood_Percent=_v_31) when st(convertible::fast)) when Tic
LUSEND
*/
   _real pHood_Percent;

/*
LUSDEF:pHood_Percent
(0.0 -> _v_20) when Tic
LUSEND
*/
   _real slow_it_down;

/*
LUSDEF:slow_it_down
((convertible::sqrt(_v_24)) when st(convertible::slow)) when Tic
LUSEND
*/
   _real pHood_Speed;

/*
LUSDEF:pHood_Speed
0.0 -> _v_26
LUSEND
*/

  if (Tic == _true) {
  Lustre_pre_2_get(&_v_13,&ctx->Lustre_pre_2_ctx_tab[0]); 
  Lustre_arrow_2_step(convertible_wait,_v_13,&pst,&ctx->Lustre_arrow_2_ctx_tab[0]); 
  Lustre_pre_3_get(&_v_20,&ctx->Lustre_pre_3_ctx_tab[0]); 
  Lustre_arrow_3_step(0.0,_v_20,&pHood_Percent,&ctx->Lustre_arrow_3_ctx_tab[0]); 
  if (pst == convertible_fast) {
  _v_14 = pHood_Percent;
  _v_15 = _v_14 < 85.0;
   if (_v_15 == _true) {
     _v_16 = convertible_fast;
   } else {
     _v_16 = convertible_slow;
   }
  st = _v_16;

  } else {
  if (pst == convertible_slow) {
  _v_17 = pHood_Percent;
  _v_18 = _v_17 < 100.0;
   if (_v_18 == _true) {
     _v_19 = convertible_slow;
   } else {
     _v_19 = convertible_wait;
   }
  st = _v_19;

  } else {
  if (pst == convertible_wait) {
  st = convertible_fast;

  } else {
  }}}  Lustre_pre_2_set(st,&ctx->Lustre_pre_2_ctx_tab[0]); 
  Lustre_slash_step(5.,0.1,&_v_25); 
  Lustre_slash_step(100.,_v_25,&kh); 
  _v_30 = kh + pHood_Percent;
  if (st == convertible_fast) {
  _v_31 = _v_30;
  Hood_Percent = _v_31;

  } else {
  if (st == convertible_slow) {
  _v_34 = pHood_Percent;
  _v_21 = pHood_Percent;
  _v_22 = 100.0 - _v_21;
  Lustre_slash_step(_v_22,5.0,&_v_23); 
  convertible_sqrt_step(_v_23,&_v_24); 
  convertible_sqrt_step(_v_24,&slow_it_down); 
  _v_32 = kh;
  _v_33 = slow_it_down * _v_32;
  _v_35 = _v_33 + _v_34;
  Hood_Percent = _v_35;

  } else {
  if (st == convertible_wait) {
  Hood_Percent = 0.0;
  Hood_Percent = 0.0;

  } else {
  }}}  Lustre_pre_3_set(Hood_Percent,&ctx->Lustre_pre_3_ctx_tab[0]); 

  } else {
  }  Lustre_pre_3_get(&_v_26,&ctx->Lustre_pre_3_ctx_tab[1]); 
  Lustre_arrow_3_step(0.0,_v_26,&pHood_Speed,&ctx->Lustre_arrow_3_ctx_tab[1]); 
  if (Tic == _false) {
  _v_27 = pHood_Speed;
  *Hood_Speed = _v_27;

  } else {
  if (Tic == _true) {
  if (st == convertible_fast) {
  _v_29 = 10.0;
  _v_29 = 10.0;

  } else {
  if (st == convertible_slow) {
  _v_28 = 10.0 * slow_it_down;
  _v_29 = _v_28;

  } else {
  if (st == convertible_wait) {
  _v_29 = 0.0;
  _v_29 = 0.0;

  } else {
  }}}  *Hood_Speed = _v_29;

  } else {
  }}  Lustre_pre_3_set(*Hood_Speed,&ctx->Lustre_pre_3_ctx_tab[1]); 

} // End of convertible_hood_speed_step

// Memory initialisation for convertible_main_ctx
void convertible_main_ctx_reset(convertible_main_ctx_type* ctx){
  int _i;

    convertible_vehicle_ctx_reset(&ctx->convertible_vehicle_ctx_tab[0]);
    convertible_speed_kmh_ctx_reset(&ctx->convertible_speed_kmh_ctx_tab[0]);
    convertible_may_collide_ctx_reset(&ctx->convertible_may_collide_ctx_tab[0]);
    convertible_hood_ctx_reset(&ctx->convertible_hood_ctx_tab[0]);
}

// Initialisation of the  internal structure of convertible_main_ctx
void convertible_main_ctx_init(convertible_main_ctx_type* ctx){
  // ctx->client_data = cdata;
  convertible_main_ctx_reset(ctx);
 }
// Step function(s) for convertible_main_ctx
void convertible_main_step(_boolean Start,_boolean Parked,_boolean Rot,_boolean Tic,_boolean OnOff,_boolean Done,_real Distance,_boolean *Danger,_boolean *Locked,_real *Speed,_real *Hood_Speed,convertible_main_ctx_type* ctx){   _boolean _v_38;

/*
LUSDEF:_v_38
(convertible::may_collide(_v_36,_v_37)) when St(convertible::anti_col)
LUSEND
*/
   _real _v_37;

/*
LUSDEF:_v_37
(_v_37=Distance) when St(convertible::anti_col)
LUSEND
*/
   _real _v_36;

/*
LUSDEF:_v_36
(_v_36=Speed) when St(convertible::anti_col)
LUSEND
*/
   convertible_vehicle_state St;

/*
LUSDEF:St
convertible::vehicle(Start,Locked,Speed,Distance)
LUSEND
*/
   _boolean _v_39;

/*
LUSDEF:_v_39
OnOff and Start
LUSEND
*/
   _boolean _v_40;

/*
LUSDEF:_v_40
not(_v_39)
LUSEND
*/

  _v_39 = OnOff & Start;
  _v_40 = ! _v_39;
  convertible_hood_step(Tic,Parked,OnOff,Done,Locked,Hood_Speed,&ctx->convertible_hood_ctx_tab[0]); 
  convertible_speed_kmh_step(Rot,Tic,Speed,&ctx->convertible_speed_kmh_ctx_tab[0]); 
  convertible_vehicle_step(Start,*Locked,*Speed,Distance,&St,&ctx->convertible_vehicle_ctx_tab[0]); 
  if (St == convertible_anti_col) {
  _v_37 = Distance;
  _v_36 = *Speed;
  convertible_may_collide_step(_v_36,_v_37,&_v_38,&ctx->convertible_may_collide_ctx_tab[0]); 
  *Danger = _v_38;

  } else {
  if (St == convertible_run) {
  *Danger = _false;
  *Danger = _false;

  } else {
  if (St == convertible_stationnary) {
  *Danger = _false;
  *Danger = _false;

  } else {
  }}}
} // End of convertible_main_step

// Step function(s) for convertible_maxr_ctx
void convertible_maxr_step(_real x,_real y,_real *res){
   _boolean _v_41;

/*
LUSDEF:_v_41
x<y
LUSEND
*/

  _v_41 = x < y;
   if (_v_41 == _true) {
     *res = y;
   } else {
     *res = x;
   }

} // End of convertible_maxr_step

// Memory initialisation for convertible_may_collide_ctx
void convertible_may_collide_ctx_reset(convertible_may_collide_ctx_type* ctx){
  int _i;

    Lustre_pre_3_ctx_reset(&ctx->Lustre_pre_3_ctx_tab[0]);
    Lustre_arrow_3_ctx_reset(&ctx->Lustre_arrow_3_ctx_tab[0]);
}

// Initialisation of the  internal structure of convertible_may_collide_ctx
void convertible_may_collide_ctx_init(convertible_may_collide_ctx_type* ctx){
  // ctx->client_data = cdata;
  convertible_may_collide_ctx_reset(ctx);
 }
// Step function(s) for convertible_may_collide_ctx
void convertible_may_collide_step(_real Speed,_real Distance,_boolean *Res,convertible_may_collide_ctx_type* ctx){   _real _v_47;

/*
LUSDEF:_v_47
2.0+tBrake
LUSEND
*/
   _real _v_46;

/*
LUSDEF:_v_46
-2.0*Distance
LUSEND
*/
   _real _v_45;

/*
LUSDEF:_v_45
2.0*Speed
LUSEND
*/
   _real _v_44;

/*
LUSDEF:_v_44
_v_43/0.1
LUSEND
*/
   _real _v_43;

/*
LUSDEF:_v_43
Speed-_v_42
LUSEND
*/
   _real _v_42;

/*
LUSDEF:_v_42
pre(Speed)
LUSEND
*/
   _real Accel;

/*
LUSDEF:Accel
0.0 -> _v_44
LUSEND
*/
   _real tChoc;

/*
LUSDEF:tChoc
convertible::solve_eq_d2(Accel,_v_45,_v_46)
LUSEND
*/
   _real tBrake;

/*
LUSDEF:tBrake
convertible::braking_time(Speed)
LUSEND
*/

  Lustre_pre_3_get(&_v_42,&ctx->Lustre_pre_3_ctx_tab[0]); 
  _v_43 = Speed - _v_42;
  Lustre_slash_step(_v_43,0.1,&_v_44); 
  Lustre_pre_3_set(Speed,&ctx->Lustre_pre_3_ctx_tab[0]); 
  Lustre_arrow_3_step(0.0,_v_44,&Accel,&ctx->Lustre_arrow_3_ctx_tab[0]); 
  convertible_braking_time_step(Speed,&tBrake); 
  _v_46 = -2.0 * Distance;
  _v_45 = 2.0 * Speed;
  convertible_solve_eq_d2_step(Accel,_v_45,_v_46,&tChoc); 
  _v_47 = 2.0 + tBrake;
  *Res = tChoc < _v_47;

} // End of convertible_may_collide_step

// Step function(s) for convertible_ms_to_kmh_ctx
void convertible_ms_to_kmh_step(_real x,_real *res){

  *res = x * 3.6;

} // End of convertible_ms_to_kmh_step

// Step function(s) for convertible_solve_eq_d2_ctx
void convertible_solve_eq_d2_step(_real a,_real b,_real c,_real *res){
   _real _v_75;

/*
LUSDEF:_v_75
(convertible::maxr(_v_69,_v_74)) when sol_nb(convertible::two_sol)
LUSEND
*/
   _real _v_74;

/*
LUSDEF:_v_74
(_v_70-_v_73) when sol_nb(convertible::two_sol)
LUSEND
*/
   _real _v_73;

/*
LUSDEF:_v_73
(_v_71/_v_72) when sol_nb(convertible::two_sol)
LUSEND
*/
   _real _v_72;

/*
LUSDEF:_v_72
(2.0*a2) when sol_nb(convertible::two_sol)
LUSEND
*/
   _real _v_71;

/*
LUSDEF:_v_71
(convertible::sqrt(delta_pos)) when sol_nb(convertible::two_sol)
LUSEND
*/
   _real _v_70;

/*
LUSDEF:_v_70
(-b2) when sol_nb(convertible::two_sol)
LUSEND
*/
   _real _v_69;

/*
LUSDEF:_v_69
(_v_65+_v_68) when sol_nb(convertible::two_sol)
LUSEND
*/
   _real _v_68;

/*
LUSDEF:_v_68
(_v_66/_v_67) when sol_nb(convertible::two_sol)
LUSEND
*/
   _real _v_67;

/*
LUSDEF:_v_67
(2.0*a2) when sol_nb(convertible::two_sol)
LUSEND
*/
   _real _v_66;

/*
LUSDEF:_v_66
(convertible::sqrt(delta_pos)) when sol_nb(convertible::two_sol)
LUSEND
*/
   _real _v_65;

/*
LUSDEF:_v_65
(-b2) when sol_nb(convertible::two_sol)
LUSEND
*/
   _real _v_64;

/*
LUSDEF:_v_64
(_v_64=_v_63) when sol_nb(convertible::one_sol)
LUSEND
*/
   _real _v_63;

/*
LUSDEF:_v_63
_v_61/_v_62
LUSEND
*/
   _real _v_62;

/*
LUSDEF:_v_62
2.0*a
LUSEND
*/
   _real _v_61;

/*
LUSDEF:_v_61
-b
LUSEND
*/
   _real _v_60;

/*
LUSDEF:_v_60
(_v_60=_v_59) when sol_nb(convertible::deg1)
LUSEND
*/
   _real _v_59;

/*
LUSDEF:_v_59
_v_58/b
LUSEND
*/
   _real _v_58;

/*
LUSDEF:_v_58
-c
LUSEND
*/
   convertible_eq_case _v_57;

/*
LUSDEF:_v_57
if _v_54 then convertible_no_sol else _v_56
LUSEND
*/
   convertible_eq_case _v_56;

/*
LUSDEF:_v_56
if _v_55 then convertible_one_sol else convertible_two_sol
LUSEND
*/
   _boolean _v_55;

/*
LUSDEF:_v_55
delta=0.0
LUSEND
*/
   _boolean _v_54;

/*
LUSDEF:_v_54
delta<0.0
LUSEND
*/
   convertible_eq_case _v_53;

/*
LUSDEF:_v_53
if _v_52 then convertible_no_sol else convertible_deg1
LUSEND
*/
   _boolean _v_52;

/*
LUSDEF:_v_52
b=0.0
LUSEND
*/
   _boolean _v_51;

/*
LUSDEF:_v_51
a=0.0
LUSEND
*/
   _real _v_50;

/*
LUSDEF:_v_50
_v_49*c
LUSEND
*/
   _real _v_49;

/*
LUSDEF:_v_49
4.0*a
LUSEND
*/
   _real _v_48;

/*
LUSDEF:_v_48
b*b
LUSEND
*/
   _real delta;

/*
LUSDEF:delta
_v_48-_v_50
LUSEND
*/
   convertible_eq_case sol_nb;

/*
LUSDEF:sol_nb
if _v_51 then _v_53 else _v_57
LUSEND
*/
   _real a2;

/*
LUSDEF:a2
(a2=a) when sol_nb(convertible::two_sol)
LUSEND
*/
   _real b2;

/*
LUSDEF:b2
(b2=b) when sol_nb(convertible::two_sol)
LUSEND
*/
   _real delta_pos;

/*
LUSDEF:delta_pos
(delta_pos=delta) when sol_nb(convertible::two_sol)
LUSEND
*/

  _v_49 = 4.0 * a;
  _v_50 = _v_49 * c;
  _v_48 = b * b;
  delta = _v_48 - _v_50;
  Lustre_eq_2_step(delta,0.0,&_v_55); 
   if (_v_55 == _true) {
     _v_56 = convertible_one_sol;
   } else {
     _v_56 = convertible_two_sol;
   }
  _v_54 = delta < 0.0;
   if (_v_54 == _true) {
     _v_57 = convertible_no_sol;
   } else {
     _v_57 = _v_56;
   }
  Lustre_eq_2_step(b,0.0,&_v_52); 
   if (_v_52 == _true) {
     _v_53 = convertible_no_sol;
   } else {
     _v_53 = convertible_deg1;
   }
  Lustre_eq_2_step(a,0.0,&_v_51); 
   if (_v_51 == _true) {
     sol_nb = _v_53;
   } else {
     sol_nb = _v_57;
   }
  if (sol_nb == convertible_two_sol) {
  delta_pos = delta;
  a2 = a;
  b2 = b;
  convertible_sqrt_step(delta_pos,&_v_66); 
  _v_67 = 2.0 * a2;
  Lustre_slash_step(_v_66,_v_67,&_v_68); 
  _v_65 = - b2;
  _v_69 = _v_65 + _v_68;
  convertible_sqrt_step(delta_pos,&_v_71); 
  _v_72 = 2.0 * a2;
  Lustre_slash_step(_v_71,_v_72,&_v_73); 
  _v_70 = - b2;
  _v_74 = _v_70 - _v_73;
  convertible_maxr_step(_v_69,_v_74,&_v_75); 

  } else {
  }  _v_61 = - b;
  _v_62 = 2.0 * a;
  Lustre_slash_step(_v_61,_v_62,&_v_63); 
  if (sol_nb == convertible_one_sol) {
  _v_64 = _v_63;

  } else {
  }  _v_58 = - c;
  Lustre_slash_step(_v_58,b,&_v_59); 
  if (sol_nb == convertible_deg1) {
  _v_60 = _v_59;
  *res = _v_60;

  } else {
  if (sol_nb == convertible_two_sol) {
  *res = _v_75;

  } else {
  if (sol_nb == convertible_one_sol) {
  *res = _v_64;

  } else {
  if (sol_nb == convertible_no_sol) {
  *res = -1.0;
  *res = -1.0;

  } else {
  }}}}
} // End of convertible_solve_eq_d2_step

// Memory initialisation for convertible_speed_kmh_ctx
void convertible_speed_kmh_ctx_reset(convertible_speed_kmh_ctx_type* ctx){
  int _i;

    sum_50_0d1_ctx_reset(&ctx->sum_50_0d1_ctx_tab[0]);
    sum_50_0d0_ctx_reset(&ctx->sum_50_0d0_ctx_tab[0]);
    Lustre_pre_3_ctx_reset(&ctx->Lustre_pre_3_ctx_tab[0]);
    Lustre_pre_3_ctx_reset(&ctx->Lustre_pre_3_ctx_tab[1]);
    Lustre_pre_3_ctx_reset(&ctx->Lustre_pre_3_ctx_tab[2]);
    Lustre_arrow_3_ctx_reset(&ctx->Lustre_arrow_3_ctx_tab[0]);
    Lustre_arrow_3_ctx_reset(&ctx->Lustre_arrow_3_ctx_tab[1]);
    Lustre_arrow_3_ctx_reset(&ctx->Lustre_arrow_3_ctx_tab[2]);
}

// Initialisation of the  internal structure of convertible_speed_kmh_ctx
void convertible_speed_kmh_ctx_init(convertible_speed_kmh_ctx_type* ctx){
  // ctx->client_data = cdata;
  convertible_speed_kmh_ctx_reset(ctx);
 }
// Step function(s) for convertible_speed_kmh_ctx
void convertible_speed_kmh_step(_boolean Rot,_boolean Tic,_real *Speed,convertible_speed_kmh_ctx_type* ctx){   _real _v_87;

/*
LUSDEF:_v_87
pre(_v_86)
LUSEND
*/
   _real _v_86;

/*
LUSDEF:_v_86
convertible::ms_to_kmh(_v_85)
LUSEND
*/
   _real _v_85;

/*
LUSDEF:_v_85
d/t
LUSEND
*/
   _real _v_84;

/*
LUSDEF:_v_84
(_v_84=_v_83) when not TicOrRot
LUSEND
*/
   _real _v_83;

/*
LUSDEF:_v_83
(_v_83=pt) when not TicOrRot
LUSEND
*/
   _real _v_82;

/*
LUSDEF:_v_82
(sum_50_0d1(_v_81)) when TicOrRot
LUSEND
*/
   _real _v_81;

/*
LUSDEF:_v_81
(_v_81=tx) when TicOrRot
LUSEND
*/
   _real _v_80;

/*
LUSDEF:_v_80
(sum_50_0d0(_v_79)) when TicOrRot
LUSEND
*/
   _real _v_79;

/*
LUSDEF:_v_79
(_v_79=dx) when TicOrRot
LUSEND
*/
   _real _v_78;

/*
LUSDEF:_v_78
(_v_78=pd) when not TicOrRot
LUSEND
*/
   _real _v_77;

/*
LUSDEF:_v_77
pre(t)
LUSEND
*/
   _real _v_76;

/*
LUSDEF:_v_76
pre(d)
LUSEND
*/
   _real d;

/*
LUSDEF:d
(d=_v_78) when not TicOrRot
LUSEND
*/
   _real t;

/*
LUSDEF:t
convertible::maxr(0.1,_v_84)
LUSEND
*/
   _real pd;

/*
LUSDEF:pd
0.0 -> _v_76
LUSEND
*/
   _real pt;

/*
LUSDEF:pt
0.0 -> _v_77
LUSEND
*/
   _real dx;

/*
LUSDEF:dx
if Rot then 1.4 else 0.0
LUSEND
*/
   _real tx;

/*
LUSDEF:tx
if Tic then 0.1 else 0.0
LUSEND
*/
   _boolean TicOrRot;

/*
LUSDEF:TicOrRot
Tic or Rot
LUSEND
*/

   if (Rot == _true) {
     dx = 1.4;
   } else {
     dx = 0.0;
   }
   if (Tic == _true) {
     tx = 0.1;
   } else {
     tx = 0.0;
   }
  TicOrRot = Tic | Rot;
  Lustre_pre_3_get(&_v_76,&ctx->Lustre_pre_3_ctx_tab[0]); 
  Lustre_arrow_3_step(0.0,_v_76,&pd,&ctx->Lustre_arrow_3_ctx_tab[0]); 
  if (TicOrRot == _false) {
  _v_78 = pd;
  d = _v_78;

  } else {
  if (TicOrRot == _true) {
  _v_79 = dx;
  sum_50_0d0_step(_v_79,&_v_80,&ctx->sum_50_0d0_ctx_tab[0]); 
  d = _v_80;

  } else {
  }}  Lustre_pre_3_set(d,&ctx->Lustre_pre_3_ctx_tab[0]); 
  Lustre_pre_3_get(&_v_77,&ctx->Lustre_pre_3_ctx_tab[1]); 
  Lustre_arrow_3_step(0.0,_v_77,&pt,&ctx->Lustre_arrow_3_ctx_tab[1]); 
  if (TicOrRot == _false) {
  _v_83 = pt;
  _v_84 = _v_83;

  } else {
  if (TicOrRot == _true) {
  _v_81 = tx;
  sum_50_0d1_step(_v_81,&_v_82,&ctx->sum_50_0d1_ctx_tab[0]); 
  _v_84 = _v_82;

  } else {
  }}  convertible_maxr_step(0.1,_v_84,&t); 
  Lustre_pre_3_set(t,&ctx->Lustre_pre_3_ctx_tab[1]); 
  Lustre_pre_3_get(&_v_87,&ctx->Lustre_pre_3_ctx_tab[2]); 
  Lustre_slash_step(d,t,&_v_85); 
  convertible_ms_to_kmh_step(_v_85,&_v_86); 
  Lustre_pre_3_set(_v_86,&ctx->Lustre_pre_3_ctx_tab[2]); 
  Lustre_arrow_3_step(0.0,_v_87,Speed,&ctx->Lustre_arrow_3_ctx_tab[2]); 

} // End of convertible_speed_kmh_step

// Step function(s) for convertible_sqrt_ctx
void convertible_sqrt_step(_real R,_real *Sqrt){

  squareR_5_step(R,1.0,Sqrt); 

} // End of convertible_sqrt_step

// Memory initialisation for convertible_vehicle_ctx
void convertible_vehicle_ctx_reset(convertible_vehicle_ctx_type* ctx){
  int _i;

    Lustre_pre_6_ctx_reset(&ctx->Lustre_pre_6_ctx_tab[0]);
    Lustre_arrow_6_ctx_reset(&ctx->Lustre_arrow_6_ctx_tab[0]);
}

// Initialisation of the  internal structure of convertible_vehicle_ctx
void convertible_vehicle_ctx_init(convertible_vehicle_ctx_type* ctx){
  // ctx->client_data = cdata;
  convertible_vehicle_ctx_reset(ctx);
 }
// Step function(s) for convertible_vehicle_ctx
void convertible_vehicle_step(_boolean Start,_boolean Locked,_real Speed,_real Distance,convertible_vehicle_state *st,convertible_vehicle_ctx_type* ctx){   convertible_vehicle_state _v_153;

/*
LUSDEF:_v_153
(if _v_152 then convertible_run else convertible_anti_col) when pst(convertible::anti_col)
LUSEND
*/
   _boolean _v_152;

/*
LUSDEF:_v_152
(not(_v_151)) when pst(convertible::anti_col)
LUSEND
*/
   _boolean _v_151;

/*
LUSDEF:_v_151
(_v_151=ac_cond) when pst(convertible::anti_col)
LUSEND
*/
   convertible_vehicle_state _v_150;

/*
LUSDEF:_v_150
(if _v_146 then convertible_anti_col else _v_149) when pst(convertible::run)
LUSEND
*/
   convertible_vehicle_state _v_149;

/*
LUSDEF:_v_149
(if _v_148 then convertible_stationnary else convertible_run) when pst(convertible::run)
LUSEND
*/
   _boolean _v_148;

/*
LUSDEF:_v_148
(_v_148=_v_147) when pst(convertible::run)
LUSEND
*/
   _boolean _v_147;

/*
LUSDEF:_v_147
Speed=0.0
LUSEND
*/
   _boolean _v_146;

/*
LUSDEF:_v_146
(_v_146=ac_cond) when pst(convertible::run)
LUSEND
*/
   convertible_vehicle_state _v_145;

/*
LUSDEF:_v_145
(if _v_144 then convertible_run else convertible_stationnary) when pst(convertible::stationnary)
LUSEND
*/
   _boolean _v_144;

/*
LUSDEF:_v_144
(_v_144=_v_143) when pst(convertible::stationnary)
LUSEND
*/
   _boolean _v_143;

/*
LUSDEF:_v_143
Start and Locked
LUSEND
*/
   convertible_vehicle_state _v_142;

/*
LUSDEF:_v_142
pre(st)
LUSEND
*/
   convertible_vehicle_state pst;

/*
LUSDEF:pst
convertible_stationnary -> _v_142
LUSEND
*/
   _boolean ac_cond;

/*
LUSDEF:ac_cond
Speed>=110.0
LUSEND
*/

  Lustre_pre_6_get(&_v_142,&ctx->Lustre_pre_6_ctx_tab[0]); 
  Lustre_arrow_6_step(convertible_stationnary,_v_142,&pst,&ctx->Lustre_arrow_6_ctx_tab[0]); 
  ac_cond = Speed >= 110.0;
  if (pst == convertible_anti_col) {
  _v_151 = ac_cond;
  _v_152 = ! _v_151;
   if (_v_152 == _true) {
     _v_153 = convertible_run;
   } else {
     _v_153 = convertible_anti_col;
   }
  *st = _v_153;

  } else {
  }  Lustre_eq_2_step(Speed,0.0,&_v_147); 
  if (pst == convertible_run) {
  _v_148 = _v_147;
   if (_v_148 == _true) {
     _v_149 = convertible_stationnary;
   } else {
     _v_149 = convertible_run;
   }
  _v_146 = ac_cond;
   if (_v_146 == _true) {
     _v_150 = convertible_anti_col;
   } else {
     _v_150 = _v_149;
   }
  *st = _v_150;

  } else {
  }  _v_143 = Start & Locked;
  if (pst == convertible_stationnary) {
  _v_144 = _v_143;
   if (_v_144 == _true) {
     _v_145 = convertible_run;
   } else {
     _v_145 = convertible_stationnary;
   }
  *st = _v_145;

  } else {
  }  Lustre_pre_6_set(*st,&ctx->Lustre_pre_6_ctx_tab[0]); 

} // End of convertible_vehicle_step

// Step function(s) for fillred_update_cell_do_50_ctx
void fillred_update_cell_do_50_step(convertible_update_acc acc,_real cell[50],convertible_update_acc *nacc,_real ncell[50]/*out*/){
  int _i;
  for (_i=0 ; _i<49 ; _i+=2){
    update_cell_do_50_step(acc,cell[_i],&acc,&ncell[_i]); 
    update_cell_do_50_step(acc,cell[_i+1],&acc,&ncell[_i+1]); 
  }
   *nacc = acc;

} // End of fillred_update_cell_do_50_step

// Step function(s) for red_rplus_50_real_ctx
void red_rplus_50_real_step(_real i1,_real i2[50],_real *o){
  int _i;
  for (_i=0 ; _i<49 ; _i+=2){
    i1 = i1 + i2[_i];
    i1 = i1 + i2[_i+1];
  }
   *o = i1;

} // End of red_rplus_50_real_step

// Step function(s) for squareR_1_ctx
void squareR_1_step(_real x,_real presqrt,_real *Sqrt){
   _real _v_91;

/*
LUSDEF:_v_91
presqrt+_v_90
LUSEND
*/
   _real _v_90;

/*
LUSDEF:_v_90
x/presqrt
LUSEND
*/
   _real _v_89;

/*
LUSDEF:_v_89
convertible::abs(_v_88)
LUSEND
*/
   _real _v_88;

/*
LUSDEF:_v_88
presqrt-sqrt
LUSEND
*/
   _real sqrt;

/*
LUSDEF:sqrt
0.5*_v_91
LUSEND
*/
   _boolean ecart;

/*
LUSDEF:ecart
_v_89<0.0005
LUSEND
*/

  Lustre_slash_step(x,presqrt,&_v_90); 
  _v_91 = presqrt + _v_90;
  sqrt = 0.5 * _v_91;
  _v_88 = presqrt - sqrt;
  convertible_abs_step(_v_88,&_v_89); 
  ecart = _v_89 < 0.0005;
  *Sqrt = sqrt;

} // End of squareR_1_step

// Step function(s) for squareR_2_ctx
void squareR_2_step(_real x,_real presqrt,_real *Sqrt){
   _real _v_99;

/*
LUSDEF:_v_99
(_v_99=sqrt) when ecart
LUSEND
*/
   _real _v_98;

/*
LUSDEF:_v_98
(squareR_1(_v_96,_v_97)) when not ecart
LUSEND
*/
   _real _v_97;

/*
LUSDEF:_v_97
(_v_97=sqrt) when not ecart
LUSEND
*/
   _real _v_96;

/*
LUSDEF:_v_96
(_v_96=x) when not ecart
LUSEND
*/
   _real _v_95;

/*
LUSDEF:_v_95
presqrt+_v_94
LUSEND
*/
   _real _v_94;

/*
LUSDEF:_v_94
x/presqrt
LUSEND
*/
   _real _v_93;

/*
LUSDEF:_v_93
convertible::abs(_v_92)
LUSEND
*/
   _real _v_92;

/*
LUSDEF:_v_92
presqrt-sqrt
LUSEND
*/
   _real sqrt;

/*
LUSDEF:sqrt
0.5*_v_95
LUSEND
*/
   _boolean ecart;

/*
LUSDEF:ecart
_v_93<0.0005
LUSEND
*/

  Lustre_slash_step(x,presqrt,&_v_94); 
  _v_95 = presqrt + _v_94;
  sqrt = 0.5 * _v_95;
  _v_92 = presqrt - sqrt;
  convertible_abs_step(_v_92,&_v_93); 
  ecart = _v_93 < 0.0005;
  if (ecart == _true) {
  _v_99 = sqrt;
  *Sqrt = _v_99;

  } else {
  if (ecart == _false) {
  _v_97 = sqrt;
  _v_96 = x;
  squareR_1_step(_v_96,_v_97,&_v_98); 
  *Sqrt = _v_98;

  } else {
  }}
} // End of squareR_2_step

// Step function(s) for squareR_3_ctx
void squareR_3_step(_real x,_real presqrt,_real *Sqrt){
   _real _v_107;

/*
LUSDEF:_v_107
(_v_107=sqrt) when ecart
LUSEND
*/
   _real _v_106;

/*
LUSDEF:_v_106
(squareR_2(_v_104,_v_105)) when not ecart
LUSEND
*/
   _real _v_105;

/*
LUSDEF:_v_105
(_v_105=sqrt) when not ecart
LUSEND
*/
   _real _v_104;

/*
LUSDEF:_v_104
(_v_104=x) when not ecart
LUSEND
*/
   _real _v_103;

/*
LUSDEF:_v_103
presqrt+_v_102
LUSEND
*/
   _real _v_102;

/*
LUSDEF:_v_102
x/presqrt
LUSEND
*/
   _real _v_101;

/*
LUSDEF:_v_101
convertible::abs(_v_100)
LUSEND
*/
   _real _v_100;

/*
LUSDEF:_v_100
presqrt-sqrt
LUSEND
*/
   _real sqrt;

/*
LUSDEF:sqrt
0.5*_v_103
LUSEND
*/
   _boolean ecart;

/*
LUSDEF:ecart
_v_101<0.0005
LUSEND
*/

  Lustre_slash_step(x,presqrt,&_v_102); 
  _v_103 = presqrt + _v_102;
  sqrt = 0.5 * _v_103;
  _v_100 = presqrt - sqrt;
  convertible_abs_step(_v_100,&_v_101); 
  ecart = _v_101 < 0.0005;
  if (ecart == _true) {
  _v_107 = sqrt;
  *Sqrt = _v_107;

  } else {
  if (ecart == _false) {
  _v_105 = sqrt;
  _v_104 = x;
  squareR_2_step(_v_104,_v_105,&_v_106); 
  *Sqrt = _v_106;

  } else {
  }}
} // End of squareR_3_step

// Step function(s) for squareR_4_ctx
void squareR_4_step(_real x,_real presqrt,_real *Sqrt){
   _real _v_115;

/*
LUSDEF:_v_115
(_v_115=sqrt) when ecart
LUSEND
*/
   _real _v_114;

/*
LUSDEF:_v_114
(squareR_3(_v_112,_v_113)) when not ecart
LUSEND
*/
   _real _v_113;

/*
LUSDEF:_v_113
(_v_113=sqrt) when not ecart
LUSEND
*/
   _real _v_112;

/*
LUSDEF:_v_112
(_v_112=x) when not ecart
LUSEND
*/
   _real _v_111;

/*
LUSDEF:_v_111
presqrt+_v_110
LUSEND
*/
   _real _v_110;

/*
LUSDEF:_v_110
x/presqrt
LUSEND
*/
   _real _v_109;

/*
LUSDEF:_v_109
convertible::abs(_v_108)
LUSEND
*/
   _real _v_108;

/*
LUSDEF:_v_108
presqrt-sqrt
LUSEND
*/
   _real sqrt;

/*
LUSDEF:sqrt
0.5*_v_111
LUSEND
*/
   _boolean ecart;

/*
LUSDEF:ecart
_v_109<0.0005
LUSEND
*/

  Lustre_slash_step(x,presqrt,&_v_110); 
  _v_111 = presqrt + _v_110;
  sqrt = 0.5 * _v_111;
  _v_108 = presqrt - sqrt;
  convertible_abs_step(_v_108,&_v_109); 
  ecart = _v_109 < 0.0005;
  if (ecart == _true) {
  _v_115 = sqrt;
  *Sqrt = _v_115;

  } else {
  if (ecart == _false) {
  _v_113 = sqrt;
  _v_112 = x;
  squareR_3_step(_v_112,_v_113,&_v_114); 
  *Sqrt = _v_114;

  } else {
  }}
} // End of squareR_4_step

// Step function(s) for squareR_5_ctx
void squareR_5_step(_real x,_real presqrt,_real *Sqrt){
   _real _v_123;

/*
LUSDEF:_v_123
(_v_123=sqrt) when ecart
LUSEND
*/
   _real _v_122;

/*
LUSDEF:_v_122
(squareR_4(_v_120,_v_121)) when not ecart
LUSEND
*/
   _real _v_121;

/*
LUSDEF:_v_121
(_v_121=sqrt) when not ecart
LUSEND
*/
   _real _v_120;

/*
LUSDEF:_v_120
(_v_120=x) when not ecart
LUSEND
*/
   _real _v_119;

/*
LUSDEF:_v_119
presqrt+_v_118
LUSEND
*/
   _real _v_118;

/*
LUSDEF:_v_118
x/presqrt
LUSEND
*/
   _real _v_117;

/*
LUSDEF:_v_117
convertible::abs(_v_116)
LUSEND
*/
   _real _v_116;

/*
LUSDEF:_v_116
presqrt-sqrt
LUSEND
*/
   _real sqrt;

/*
LUSDEF:sqrt
0.5*_v_119
LUSEND
*/
   _boolean ecart;

/*
LUSDEF:ecart
_v_117<0.0005
LUSEND
*/

  Lustre_slash_step(x,presqrt,&_v_118); 
  _v_119 = presqrt + _v_118;
  sqrt = 0.5 * _v_119;
  _v_116 = presqrt - sqrt;
  convertible_abs_step(_v_116,&_v_117); 
  ecart = _v_117 < 0.0005;
  if (ecart == _true) {
  _v_123 = sqrt;
  *Sqrt = _v_123;

  } else {
  if (ecart == _false) {
  _v_121 = sqrt;
  _v_120 = x;
  squareR_4_step(_v_120,_v_121,&_v_122); 
  *Sqrt = _v_122;

  } else {
  }}
} // End of squareR_5_step

// Memory initialisation for sum_50_0d0_ctx
void sum_50_0d0_ctx_reset(sum_50_0d0_ctx_type* ctx){
  int _i;

    Lustre_pre_5_ctx_reset(&ctx->Lustre_pre_5_ctx_tab[0]);
    Lustre_pre_4_ctx_reset(&ctx->Lustre_pre_4_ctx_tab[0]);
    Lustre_arrow_5_ctx_reset(&ctx->Lustre_arrow_5_ctx_tab[0]);
    Lustre_arrow_4_ctx_reset(&ctx->Lustre_arrow_4_ctx_tab[0]);
}

// Initialisation of the  internal structure of sum_50_0d0_ctx
void sum_50_0d0_ctx_init(sum_50_0d0_ctx_type* ctx){
  // ctx->client_data = cdata;
  sum_50_0d0_ctx_reset(ctx);
 }
// Step function(s) for sum_50_0d0_ctx
void sum_50_0d0_step(_real s,_real *res,sum_50_0d0_ctx_type* ctx){   _integer _v_128;

/*
LUSDEF:_v_128
i mod 50
LUSEND
*/
   _real _v_127[50];

/*
LUSDEF:_v_127
pre(a)
LUSEND
*/
   _real _v_126[50];

/*
LUSDEF:_v_126
hat(0.0)
LUSEND
*/
   _integer _v_125;

/*
LUSDEF:_v_125
0 -> _v_124
LUSEND
*/
   _integer _v_124;

/*
LUSDEF:_v_124
pre(i)
LUSEND
*/
   _real a[50];

/*
LUSDEF:a
assign_50(s,_v_128,pre_a)
LUSEND
*/
   _real pre_a[50];

/*
LUSDEF:pre_a
_v_126 -> _v_127
LUSEND
*/
   _integer i;

/*
LUSDEF:i
_v_125+1
LUSEND
*/

  Lustre_pre_4_get(&_v_124,&ctx->Lustre_pre_4_ctx_tab[0]); 
  Lustre_arrow_4_step(0,_v_124,&_v_125,&ctx->Lustre_arrow_4_ctx_tab[0]); 
  i = _v_125 + 1;
  Lustre_pre_4_set(i,&ctx->Lustre_pre_4_ctx_tab[0]); 
  Lustre_pre_5_get(_v_127,&ctx->Lustre_pre_5_ctx_tab[0]); 
  Lustre_hat_step(0.0,_v_126); 
  Lustre_arrow_5_step(_v_126,_v_127,pre_a,&ctx->Lustre_arrow_5_ctx_tab[0]); 
  _v_128 = i % 50;
  assign_50_step(s,_v_128,pre_a,a); 
  Lustre_pre_5_set(a,&ctx->Lustre_pre_5_ctx_tab[0]); 
  red_rplus_50_real_step(0.0,a,res); 

} // End of sum_50_0d0_step

// Memory initialisation for sum_50_0d1_ctx
void sum_50_0d1_ctx_reset(sum_50_0d1_ctx_type* ctx){
  int _i;

    Lustre_pre_5_ctx_reset(&ctx->Lustre_pre_5_ctx_tab[0]);
    Lustre_pre_4_ctx_reset(&ctx->Lustre_pre_4_ctx_tab[0]);
    Lustre_arrow_5_ctx_reset(&ctx->Lustre_arrow_5_ctx_tab[0]);
    Lustre_arrow_4_ctx_reset(&ctx->Lustre_arrow_4_ctx_tab[0]);
}

// Initialisation of the  internal structure of sum_50_0d1_ctx
void sum_50_0d1_ctx_init(sum_50_0d1_ctx_type* ctx){
  // ctx->client_data = cdata;
  sum_50_0d1_ctx_reset(ctx);
 }
// Step function(s) for sum_50_0d1_ctx
void sum_50_0d1_step(_real s,_real *res,sum_50_0d1_ctx_type* ctx){   _integer _v_133;

/*
LUSDEF:_v_133
i mod 50
LUSEND
*/
   _real _v_132[50];

/*
LUSDEF:_v_132
pre(a)
LUSEND
*/
   _real _v_131[50];

/*
LUSDEF:_v_131
hat(0.1)
LUSEND
*/
   _integer _v_130;

/*
LUSDEF:_v_130
0 -> _v_129
LUSEND
*/
   _integer _v_129;

/*
LUSDEF:_v_129
pre(i)
LUSEND
*/
   _real a[50];

/*
LUSDEF:a
assign_50(s,_v_133,pre_a)
LUSEND
*/
   _real pre_a[50];

/*
LUSDEF:pre_a
_v_131 -> _v_132
LUSEND
*/
   _integer i;

/*
LUSDEF:i
_v_130+1
LUSEND
*/

  Lustre_pre_4_get(&_v_129,&ctx->Lustre_pre_4_ctx_tab[0]); 
  Lustre_arrow_4_step(0,_v_129,&_v_130,&ctx->Lustre_arrow_4_ctx_tab[0]); 
  i = _v_130 + 1;
  Lustre_pre_4_set(i,&ctx->Lustre_pre_4_ctx_tab[0]); 
  Lustre_pre_5_get(_v_132,&ctx->Lustre_pre_5_ctx_tab[0]); 
  Lustre_hat_step(0.1,_v_131); 
  Lustre_arrow_5_step(_v_131,_v_132,pre_a,&ctx->Lustre_arrow_5_ctx_tab[0]); 
  _v_133 = i % 50;
  assign_50_step(s,_v_133,pre_a,a); 
  Lustre_pre_5_set(a,&ctx->Lustre_pre_5_ctx_tab[0]); 
  red_rplus_50_real_step(0.0,a,res); 

} // End of sum_50_0d1_step

// Step function(s) for update_cell_do_50_ctx
void update_cell_do_50_step(convertible_update_acc acc,_real cell,convertible_update_acc *nacc,_real *ncell){
   _integer _v_139;

/*
LUSDEF:_v_139
_v_138+1
LUSEND
*/
   _integer _v_138;
   _integer _v_140;
   _real _v_141;
   _real _v_137;
   _boolean _v_136;

/*
LUSDEF:_v_136
_v_134=_v_135
LUSEND
*/
   _integer _v_135;
   _integer _v_134;

  _v_137 = acc.v;
  _v_134 = acc.i;
  _v_135 = acc.j;
  Lustre_eq_step(_v_134,_v_135,&_v_136); 
   if (_v_136 == _true) {
     *ncell = _v_137;
   } else {
     *ncell = cell;
   }
  _v_138 = acc.i;
  _v_139 = _v_138 + 1;
  _v_140 = acc.j;
  _v_141 = acc.v;
  nacc->i = _v_139;
  nacc->j = _v_140;
  nacc->v = _v_141;

} // End of update_cell_do_50_step

