/* This file was generated by lus2lic version master.668 (35901e970a0c377cc36d6437dcbc61beb8001b54). */
/*  lus2lic -2c convertible.lus -n main */
/* on ovaz the 27/10/2016 at 11:39:07 */

// Constant definitions 
#define convertible_anti_col 2
#define convertible_deg1 1
#define convertible_fast 1
#define convertible_in_motion 1
#define convertible_k 5500.0
#define convertible_locked 0
#define convertible_max_hood_speed 10.0
#define convertible_no_sol 0
#define convertible_one_sol 2
#define convertible_period 0.1
#define convertible_run 1
#define convertible_size 50
#define convertible_slow 2
#define convertible_speed_max 110.0
#define convertible_stationnary 0
#define convertible_two_sol 3
#define convertible_wait 0
#define convertible_wheel_girth 1.4
