/* This file was generated by lus2lic version master.671 (480ff8adfdc23a03f88ab2796a74a7ecb75975f1). */
/*  lus2lic -2cw7 -2cns ../convertible.lus -n main */
/* on ovaz the 21/11/2016 at 13:49:49 */

#ifndef _SOC2C_PREDEF_TYPES
#define _SOC2C_PREDEF_TYPES
typedef int _boolean;
typedef int _integer;
typedef char* _string;
typedef double _real;
typedef double _double;
typedef float _float;
#define _false 0
#define _true 1
#endif
// end of _SOC2C_PREDEF_TYPES
// User typedef 
#ifndef _convertible_main_TYPES
#define _convertible_main_TYPES
typedef _integer convertible_eq_case;
typedef _integer convertible_hood_speed_state;
typedef _integer convertible_hood_state;
typedef struct { 
   _integer i;
   _integer j;
   _real v;
  } convertible_update_acc;
typedef _integer convertible_vehicle_state;
#endif // enf of  _convertible_main_TYPES
// Defining array and extern types assignments 

#ifndef _assign_rp50 
#define _assign_rp50(dest, source, size) memcpy(dest, source, size)
#endif
